FROM quay.io/aipcc/base-images/cpu:3.5.0@sha256:a398ebc954964790a18157c50bf36656f358005786e46273b87f885d78909d5d AS cpu-base
FROM quay.io/aipcc/base-images/cuda-12.9-el9.6:3.5.0@sha256:49dd116addf206d555b6c9532cd9d90f93730d8db4363ffe9b8901c34ecd51e1 AS cuda-base

FROM cpu-base AS base-ppc64le
FROM cpu-base AS base-s390x
FROM cuda-base AS base-amd64
FROM cuda-base AS base-arm64

ARG TARGETARCH
FROM base-${TARGETARCH}
USER root

ARG TARGETARCH
ARG PYLOCK_FLAVOR=${TARGETARCH}

RUN sed -i.bak 's/include-system-site-packages = false/include-system-site-packages = true/' /opt/app-root/pyvenv.cfg

WORKDIR /opt/app-root/src
COPY . .

RUN pip install --no-cache-dir --no-deps --require-hashes \
        -r requirements-build.txt

RUN if [ "$PYLOCK_FLAVOR" = "ppc64le" ] || [ "$PYLOCK_FLAVOR" = "s390x" ]; then \
        pip install --no-cache-dir --no-deps --require-hashes \
            -r requirements.hf-cpu.txt; \
    else \
        pip install --no-cache-dir --no-deps --require-hashes \
            -r requirements.hf-cuda.txt; \
    fi

RUN pip install --no-cache-dir --no-deps .

WORKDIR /app
COPY ./common /app/detectors/common
COPY ./huggingface/detector.py /app/detectors/huggingface/
RUN mkdir /common; cp /app/detectors/common/log_conf.yaml /common/
COPY ./huggingface/app.py /app
ENV PROMETHEUS_MULTIPROC_DIR="/tmp/prometheus_multiproc_dir"
RUN mkdir -p $PROMETHEUS_MULTIPROC_DIR && chmod 777 $PROMETHEUS_MULTIPROC_DIR

USER 1001
EXPOSE 8000
CMD ["uvicorn", "app:app", "--workers", "1", "--host", "0.0.0.0", "--port", "8000", "--log-config", "/common/log_conf.yaml"]

LABEL name="rhoai/odh-guardrails-detector-huggingface-runtime-rhel9" \
      com.redhat.component="odh-guardrails-detector-huggingface-runtime-rhel9" \
      io.k8s.display-name="odh-guardrails-detector-huggingface-runtime-rhel9" \
      io.k8s.description="A HuggingFace-based generic detector designed for compatibility with any AutoModelForSequenceClassification or the GraniteForCausalLM model." \
      description="A HuggingFace-based generic detector designed for compatibility with any AutoModelForSequenceClassification or the GraniteForCausalLM model." \
      summary="A HuggingFace-based generic detector designed for compatibility with any AutoModelForSequenceClassification or the GraniteForCausalLM model." \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
