FROM quay.io/aipcc/base-images/cpu:3.5.0@sha256:a398ebc954964790a18157c50bf36656f358005786e46273b87f885d78909d5d
USER root

RUN sed -i.bak 's/include-system-site-packages = false/include-system-site-packages = true/' /opt/app-root/pyvenv.cfg

WORKDIR /opt/app-root/src
COPY . .

RUN pip install --no-cache-dir --no-deps --require-hashes \
        -r requirements-build.txt

RUN pip install --no-cache-dir --no-deps --require-hashes \
        -r requirements.builtIn.txt

RUN pip install --no-cache-dir --no-deps .

WORKDIR /app
COPY ./common /app/detectors/common
COPY ./built_in/ /app

EXPOSE 8080

# for backwards compatibility with existing k8s deployment configs
RUN mkdir /app/bin &&\
     echo '#!/bin/bash' > /app/bin/regex-detector &&\
    echo "uvicorn app:app --workers 4 --host 0.0.0.0 --port 8080 --log-config /app/detectors/common/log_conf.yaml" >> /app/bin/regex-detector &&\
    chmod +x /app/bin/regex-detector

USER 1001
CMD ["/app/bin/regex-detector"]

LABEL name="rhoai/odh-built-in-detector-rhel9" \
      com.redhat.component="odh-built-in-detector-rhel9" \
      io.k8s.display-name="odh-built-in-detector-rhel9" \
      io.k8s.description="The Guardrails Built-in Detector is a collection of quick text detection algorithms, bundled into a microservice for use with the FMS-Guardrails project. It provides a REST API endpoint that accepts text content and detector parameters, returning detailed detection results with position information and confidence scores for a variety of text detection paradigms, such as regex and file-type validation." \
      description="The Guardrails Built-in Detector is a collection of quick text detection algorithms, bundled into a microservice for use with the FMS-Guardrails project. It provides a REST API endpoint that accepts text content and detector parameters, returning detailed detection results with position information and confidence scores for a variety of text detection paradigms, such as regex and file-type validation." \
      summary="The Guardrails Built-in Detector is a collection of quick text detection algorithms, bundled into a microservice for use with the FMS-Guardrails project." \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
