#!/usr/bin/env python3
"""Extract native (platform-specific) packages from a pip requirements file.

Native packages produce architecture-specific wheels and are identified by
having multiple ``--hash=`` lines in the lockfile (one hash per arch wheel).
Pure-Python packages have exactly one hash (the single ``py3-none-any`` wheel).

Usage:
    python extract_native_requirements.py INPUT_FILE OUTPUT_FILE
"""

from __future__ import annotations

import sys
from pathlib import Path


def _flush_entry(
    lines: list[str], hash_count: int, entries: list[tuple[str, int]]
) -> None:
    if lines:
        entries.append(("\n".join(lines), hash_count))


def extract_native_entries(text: str) -> str:
    """Return requirement entries that have 2+ ``--hash=`` lines.

    Args:
        text: Full contents of a ``requirements.txt`` lockfile generated by
            ``uv pip compile --generate-hashes``.

    Returns:
        A string containing only the ``--index-url`` header and entries with
        multiple hashes (native/platform-specific packages).
    """
    header_lines: list[str] = []
    entries: list[tuple[str, int]] = []

    current_lines: list[str] = []
    hash_count = 0
    in_entries = False

    for line in text.splitlines():
        stripped = line.strip()

        if not stripped:
            _flush_entry(current_lines, hash_count, entries)
            current_lines = []
            hash_count = 0
            continue

        if stripped.startswith("--index-url"):
            _flush_entry(current_lines, hash_count, entries)
            current_lines = []
            hash_count = 0
            header_lines.append(line)
            continue

        is_indented = line.startswith(" ") or line.startswith("\t")

        if is_indented:
            current_lines.append(line)
            if "--hash=" in stripped:
                hash_count += 1
            continue

        if stripped.startswith("#") and not in_entries:
            header_lines.append(line)
            continue

        if not stripped.startswith("#") and not stripped.startswith("--"):
            _flush_entry(current_lines, hash_count, entries)
            current_lines = []
            hash_count = 0
            in_entries = True

        current_lines.append(line)
        if "--hash=" in stripped:
            hash_count += 1

    _flush_entry(current_lines, hash_count, entries)

    native_entries = [entry for entry, count in entries if count >= 2]

    gen_header = [
        "# This file contains only native (platform-specific) packages extracted",
        "# from the full CPU requirements. Pure-Python (py3-none-any) packages are",
        "# excluded to avoid checksum collisions with the CUDA prefetch entry.",
        "#",
        "# To regenerate:  make -C detectors hf-cpu-requirements",
    ]
    parts = gen_header + header_lines + [""] + native_entries + [""]
    return "\n".join(parts)


def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} INPUT_FILE OUTPUT_FILE", file=sys.stderr)
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    if not input_path.exists():
        print(f"Error: {input_path} does not exist", file=sys.stderr)
        sys.exit(1)

    text = input_path.read_text()
    result = extract_native_entries(text)
    output_path.write_text(result)

    pkg_lines = [
        line
        for line in result.splitlines()
        if line
        and not line.startswith("#")
        and not line.startswith("--")
        and not line.startswith(" ")
    ]
    print(f"Extracted {len(pkg_lines)} native packages to {output_path}")


if __name__ == "__main__":
    main()
